version: "3.8"
services:
  db:
    container_name: db
    image: bitnami/postgresql:16.1.0
    restart: always
    volumes:
      - app-db-data:/bitnami/postgresql
    environment:
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -h ${POSTGRES_SERVER} -p ${POSTGRES_PORT} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    build:
      context: .
    restart: always
    depends_on:
      - db
    volumes:
      - .:/api
    ports:
      - "8000:${BACKEND_PORT}"
    environment:
      ENV: development

  # redis:
  #   image: redis:7.2.4
  #   restart: on-failure
  #   ports:
  #     - 6379
  #   volumes:
  #     - ./redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  app-db-data: